const ACCESS_KEY_ENTERED = 'ACCESS_KEY_ENTERED';
const SEARCH = 'SEARCH_CODE';
const FETCHING_STARTED = 'FETCHING_STARTED'
const FETCHING_ENDED = 'FETCHING_ENDED'
const FETCHED_CODE_SEARCH = 'FETCHED_CODE_SEARCH'
const FETCHED_REPOSITORIES = 'FETCHED_REPOSITORIES'
const FETCHED_PRs = 'FETCHED_PRs'
const CLEAR_FILTERS = 'CLEAR_FILTERS'
const FETCHED_COMMITS = 'FETCHED_COMMITS'
const NEW_FILTER = 'NEW_FILTER'
const FETCHED_PR_REVIEWS = 'FETCHED_PR_REVIEWS'
const FETCHED_INVOLVES = 'FETCHED_INVOLVES'
const FETCHED_USERS = 'FETCHED_USERS'
const MENU_SELECTED = 'MENU_SELECTED'
const FETCHED_ORGS = 'FETCHED_ORGS'
const ORG_SELECTED = 'ORG_SELECTED'


export {
    ORG_SELECTED,
    FETCHED_ORGS,
    ACCESS_KEY_ENTERED,
    SEARCH,
    FETCHING_STARTED,
    FETCHING_ENDED,
    FETCHED_CODE_SEARCH,
    FETCHED_REPOSITORIES,
    FETCHED_PRs,
    CLEAR_FILTERS,
    FETCHED_COMMITS,
    NEW_FILTER,
    FETCHED_PR_REVIEWS,
    FETCHED_INVOLVES,
    FETCHED_USERS,
    MENU_SELECTED
}